import "~/styles/globals.css";

import { ClerkProvider } from '@clerk/nextjs';

import { type Metadata } from "next";

import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "Midjourney Showcase",
  description: "Generated by Daryl",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`flex flex-col gap-4`}>
      <body>
        <TopNav />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
