import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from '@clerk/nextjs';

import { type Metadata } from "next";

import { TopNav } from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
  title: "Midjourney Showcase",
  description: "Generated by Daryl",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ 
  children: React.ReactNode,
  modal: React.ReactNode,
 }>) {
  return (
    <ClerkProvider>
    <html lang="en" className="">
      <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
      <body>
        <div className="h-screen grid grid-rows-[auto,1fr]">
          <TopNav />
          <main className="overflow-y-scroll">
            {children}
          </main>
        </div>
        {modal}
        <div id="modal-root" />
      </body>
    </html>
    </ClerkProvider>
  );
}
